runtime bundle/vim-pathogen/autoload/pathogen.vim
execute pathogen#infect()

filetype plugin indent on
set ofu=syntaxcomplete#Complete
syntax enable

set tabstop=2
set shiftwidth=2
set expandtab
set autoindent

set t_Co=256
set background=dark
colorscheme solarized
call togglebg#map("<F5>")
