call plug#begin('~/.vim/plugged')
Plug 'morhetz/gruvbox'
call plug#end()

set ofu=syntaxcomplete#Complete

set tabstop=2
set shiftwidth=2
set expandtab
set autoindent

set t_Co=256
let g:gruvbox_italic=1
colorscheme gruvbox
call togglebg#map("<F5>")
